<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Learning-objectives" data-toc-modified-id="Learning-objectives-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Learning objectives</a></span></li><li><span><a href="#Importing-numpy" data-toc-modified-id="Importing-numpy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Importing numpy</a></span></li><li><span><a href="#NumPy-Arrays" data-toc-modified-id="NumPy-Arrays-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>NumPy Arrays</a></span></li><li><span><a href="#So-many-ways-of-creating-arrays" data-toc-modified-id="So-many-ways-of-creating-arrays-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>So many ways of creating arrays</a></span></li><li><span><a href="#Slicing-and-indexing" data-toc-modified-id="Slicing-and-indexing-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Slicing and indexing</a></span></li><li><span><a href="#Shape-and-size" data-toc-modified-id="Shape-and-size-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Shape and size</a></span><ul class="toc-item"><li><span><a href="#Reshaping-arrays" data-toc-modified-id="Reshaping-arrays-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Reshaping arrays</a></span></li></ul></li><li><span><a href="#Playing-with-atomic-coordinates" data-toc-modified-id="Playing-with-atomic-coordinates-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Playing with atomic coordinates</a></span><ul class="toc-item"><li><span><a href="#Arrays-vs-Lists" data-toc-modified-id="Arrays-vs-Lists-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Arrays vs Lists</a></span></li></ul></li><li><span><a href="#Logical-comparisons" data-toc-modified-id="Logical-comparisons-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Logical comparisons</a></span></li><li><span><a href="#Sorted-arrays" data-toc-modified-id="Sorted-arrays-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Sorted arrays</a></span></li><li><span><a href="#Array-Axes" data-toc-modified-id="Array-Axes-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Array Axes</a></span><ul class="toc-item"><li><span><a href="#Geometric-center" data-toc-modified-id="Geometric-center-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>Geometric center</a></span></li><li><span><a href="#Center-of-mass" data-toc-modified-id="Center-of-mass-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span>Center of mass</a></span></li></ul></li><li><span><a href="#Calculating-bonds-with-numpy" data-toc-modified-id="Calculating-bonds-with-numpy-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Calculating bonds with numpy</a></span><ul class="toc-item"><li><span><a href="#Built-in-maths-functions" data-toc-modified-id="Built-in-maths-functions-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>Built-in maths functions</a></span></li><li><span><a href="#Some-more-built-in-functions" data-toc-modified-id="Some-more-built-in-functions-11.2"><span class="toc-item-num">11.2&nbsp;&nbsp;</span>Some more built-in functions</a></span></li></ul></li><li><span><a href="#Calculating-angles:-bond-angle-of-water" data-toc-modified-id="Calculating-angles:-bond-angle-of-water-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Calculating angles: bond angle of water</a></span></li><li><span>
<li><span><a href="#Next-notebook:-CL2_NB3_plotting.ipynb" data-toc-modified-id="Next-notebook:-CL2_NB3_plotting.ipynb-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Next notebook: <code>CL2_NB3_plotting.ipynb</code></a></span></li></ul></div>


<div class="alert alert-block alert-warning"><b>A note about Jupyter Notebooks</b> 
    
    
If you use the Jupyter Notebook for your Python interpreter, the notebook only executes the current code block.  This can have several unintended consequences. If you change a value and then go back and run an earlier code block, it will use the new value, not the first defined value, which may give you incorrect analysis.  
    
Similarly, if you open your Jupyter Notebook later, and try to run a code block in the middle, it may tell you that your variables are undefined, even though you can clearly see them defined in earlier code blocks.  But if you didn't re-run those code blocks, then Python doesn't know they exist. </div>

<img src="https://thejenkinscomic.files.wordpress.com/2020/04/hey-i-discovered-how-to-write-hidden-mouse-over-text.png">

# Working with `numpy` arrays

## Learning objectives

- Understand the differences between Python lists and `numpy` arrays.
- Creating, manipulating and doing mathematical operations with arrays.

This material has been adapted from [MolSSI](https://education.molssi.org/python-data-analysis/), [Jovian AI](https://jovian.ai/aakashns/python-numerical-computing-with-numpy) and the [Python Data Science Handbook](https://cocalc.com/share/public_paths/8b892baf91f98d0cf6172b872c8ad6694d0f7204/notebooks).


Author:
Dr Micaela Matta

<div class="alert alert-block alert-info">
    <b>Key points:</b> 
    
- `numpy` arrays which are the same size use element-wise operations when added or subtracted
- `numpy` uses something called *broadcasting* for arrays which are not the same size to allow arrays to be added or multiplied.
- You can see the documentation of various functions by typing the character `?` after the function. `numpy` also has extensive documentation online.
- `numpy` has many built in functions for math & stats. No need to reinvent the wheel!   

</div> 

## Importing numpy

To use the numpy library, we have to import it. When `numpy` is imported, it is often shortened to `np` as shown below:

In [2]:
###########################################
#                                         #
# REMEMBER: always run this cell first!   #
import numpy as np

## NumPy Arrays 

[Numpy](https://numpy.org/) is a widely used Python library for scientific computing. It has a number of useful features, including the a data structure called an *array*. 

Compared to the built-in data types `lists`, `numpy` has many features which can help you in your data analysis.


Previously, you have worked with the built-in types of `lists`. NumPy arrays seem similar, but offer some distinct advantages.

- **Numpy arrays take up less space, are faster, and have more mathematical operations associated with them.** 

- **However, unlike lists, elements in an array all have to be the same type.**


There are also differences in how lists and numpy arrays behave. We will look at some of these.

## So many ways of creating arrays

`numpy` has lots of ways to create arrays, we'll go over the most common.


We can "manually" create an array of numbers:

In [4]:
l = [73, 67, 43]

np.array(l)

array([73, 67, 43])

`np.random` is a useful library to create arrays of random numbers. Here we create an array with 10 random numbers between 0 and 1:

In [7]:
np.random.rand(10)

array([0.19171449, 0.68211257, 0.3250092 , 0.93083937, 0.76800457,
       0.54351806, 0.64832061, 0.46117534, 0.77503924, 0.07739115])

We can also conveniently pre-populate arrays of a given shape/size:

In [9]:
# all zeros
np.zeros((20))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [12]:
# all ones
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# all 10
np.full(4, 10)

array([10, 10, 10, 10])

We can also generate a series with `np.arange`. Here we make an array of numbers between `2` and `40` (excluded) with an increment of `2`:

In [15]:
# start=2, stop=40, increment=2
np.arange(2,40,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

## Slicing and indexing

Slicing and indexing arrays are some of the most common operations you'll have to do when working with arrays. 

To select the 5th element of an array:

In [16]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
x[4]

4

Now we select only the first 5 elements of an array:

In [18]:
x[:5]

array([0, 1, 2, 3, 4])

Indexing can also be used to modify parts of an array. For example, imagine we have an array of indices and we'd like to set the corresponding items in an array to some value:

In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
i = np.array([2, 1, 8, 4])
i

array([2, 1, 8, 4])

In [21]:
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


We have used the array of indices `i` to modify the corresponding elements of array `x`. This way of indexing arrays with other arrays is called **fancy indexing**.

Now we slice `x` considering elements between `[start:end]`:

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x[2:-2]

array([2, 3, 4, 5, 6, 7])

We can also use a third index, `[start:end:step]`, to select all the odd numbers in the array:

In [25]:
# from the second element to the last, selecting every other element
x[1:-1:2] 

array([1, 3, 5, 7])

Party trick! We can reverse the order of array elements:

In [26]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

<div class="alert alert-block alert-success"><b>Check your understanding: </b>
    
Select the last element of an array.

In [27]:
x[-1]

9

## Shape and size



<img src="https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays-1024x572.png" width =700>

So far we have only used 1D arrays, but sometimes it's useful to save data using 2D or 3D arrays. For instance, if we are recording a series of UV-Vis spectra as a function of temperature and/or time, or if we are running a  simulation and need to store atomic coordinates and velocities as a function of the timestep.

In [29]:
# a 2d array of shape (3,4)
arr2d = np.random.rand(3,4)
arr2d

array([[0.75462578, 0.26380807, 0.56511974, 0.14837319],
       [0.28013489, 0.97613716, 0.1263063 , 0.94560755],
       [0.57525701, 0.65057445, 0.73730033, 0.94297965]])

In [30]:
arr2d.shape

(3, 4)

In [31]:
arr2d.size

12

In [32]:
arr2d

array([[0.75462578, 0.26380807, 0.56511974, 0.14837319],
       [0.28013489, 0.97613716, 0.1263063 , 0.94560755],
       [0.57525701, 0.65057445, 0.73730033, 0.94297965]])

We can print the first column:

In [34]:
arr2d[:, 0]

array([0.75462578, 0.28013489, 0.57525701])

In [35]:
arr2d[0, :]

array([0.75462578, 0.26380807, 0.56511974, 0.14837319])

In [36]:
# a 3d array of shape (2,2,2)
arr3d = np.random.rand(2,2,2)

In [37]:
arr3d.size

8

In [38]:
arr3d

array([[[0.9725354 , 0.45510409],
        [0.8859601 , 0.92318432]],

       [[0.12532091, 0.9282865 ],
        [0.66964518, 0.21647241]]])

We can print the first row:

In [39]:
arr3d[0,:,:]

array([[0.9725354 , 0.45510409],
       [0.8859601 , 0.92318432]])

In [ ]:
np.random.randint?

<div class="alert alert-block alert-success"><b> Check your understanding: </b>
    
- Create a 3D array of all 5s.
- Create a 2D array of random integers between 1 and 100
- Create an array of shape (4,3,2)


In [40]:
np.ones((2,2,2)) *5 

array([[[5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.]]])

In [41]:
np.full((2,2,2), 5)

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

In [48]:
arr = np.random.randint(low=1, high=100, size=(2,5))
arr

array([[29, 21, 83,  3, 72],
       [67, 30, 81, 47, 62]])

In [45]:
arr.reshape(2,5)

ValueError: cannot reshape array of size 10 into shape (3,5)

In [ ]:
arr

### Reshaping arrays

We can change the number of elements in each dimension, increasing or removing dimensions:

In [ ]:
rand20 = np.random.rand(24)

In [ ]:
rand20.reshape(2,3,4) # from 1D to 3D

**NOTE:** Reshaping an array creates a new array but it doesn't *modify in place* the original one! 

In [ ]:
rand20 # 1D, same as before

In [ ]:
rand20_2D = rand20.reshape(2,3,4) # now i'm actually creating a new version of the original array

## Playing with atomic coordinates

We will start with reading in some data from an xyz file. The following block will read a file called `water.xyz` and saving two numpy arrays - one called `coordinates` with the molecular coordinates, and another called `symbols` with the element symbols.

In [49]:
#                           X               Y           Z
water_xyz = np.array([[0.00000,       0.00000,       0.11779],   # oxygen 
                      [0.00000,       0.75545,      -0.47116],   # hydrogen
                      [0.00000,      -0.75545,      -0.47116]])  # hydrogen

In [50]:
print(water_xyz)

[[ 0.       0.       0.11779]
 [ 0.       0.75545 -0.47116]
 [ 0.      -0.75545 -0.47116]]


<div class="alert alert-block alert-success"><b>Check your understanding: </b>
    
Slice the `water_xyz` array to create a new array called `oxygen_xyz` which has the x, y, and z coordinate for the oxygen atom. </div>

In [51]:
oxygen_xyz = water_xyz[0, :]

In [52]:
oxygen_xyz

array([0.     , 0.     , 0.11779])

### Arrays vs Lists

Now that we have the oxygen coordinates, let's imagine we wanted to do something to it. Let's imagine that we wanted to translate the position of the oxygen atom. We want to translate it 0.1 units in the x direction and -0.1 units in the y direction.

We could do this by defining a translation vector:

In [53]:
translation_vector = [0.1, -0.1, 0]

We could use a `for` loop to individually modify each coordinate:

In [54]:
oxygen_xyz_new = []

for dim in range(3):
    new_position = oxygen_xyz[dim] + translation_vector[dim]
    oxygen_xyz_new.append(new_position)

print(oxygen_xyz_new)

[0.1, -0.1, 0.11779]


However, since `oxygen_xyz` is a `numpy` array, we could have done this differently..


**Unlike for lists, you can easily perform element-wise operations on numpy arrays without loops.** You can make your code much faster if you use `numpy`'s element-by-element operations instead of loops. 

`numpy` is smart. If given two arrays (or a list and an array), it will guess that you want to do element-wise addition. 

In the `for` loop we just wrote, we actually wanted an answer that looked like

$[x_1 + x_2, y_1+ y_2, z_1+z_2] $

where $[x_1, x_2, x_3]$ was `oxygen_xyz` and $[y_1, y_2, y_3]$ was `translation_vector`. 


Using the power of `numpy` arrays, we could have instead written:

In [55]:
oxygen_xyz_new = oxygen_xyz + translation_vector # element-wise addition
print(oxygen_xyz_new)

[ 0.1     -0.1      0.11779]


`numpy` is smart - it looked at the shape of both of these variables, saw they were the same shape, and assumed we wanted to do element-wise operation. 

You could have also subtracted, multiplied, or divided these, and it would have performed element-wise operations.

Note, that this only worked because `oxygen_xyz` was a `numpy` array.

In [56]:
type(oxygen_xyz)

numpy.ndarray

What happens if we try this with a list?

In [57]:
oxygen_list = list(oxygen_xyz)
type(oxygen_list)

list

In [58]:
oxygen_translation = oxygen_list + translation_vector
oxygen_translation

[0.0, 0.0, 0.11779, 0.1, -0.1, 0]

In [59]:
type(oxygen_translation)

list

We can then convert between list and array:

In [ ]:
np.array(oxygen_translation)

Side note: if you wanted to concatenate the two where `oxygen_xyz` was a numpy array, you could have done so with the `np.concatenate` function:

In [60]:
np.concatenate((oxygen_xyz, translation_vector))

array([ 0.     ,  0.     ,  0.11779,  0.1    , -0.1    ,  0.     ])

In [62]:
np.ones((2,2)) *5 # this is element-wise multiplication  

array([[5., 5.],
       [5., 5.]])

<div class="alert alert-block alert-info">
    <b>Key points:</b> 
    
You can add two arrays together, multiply arrays by scalars, or do element-wise multiplication of arrays.

For example, you can multiply two numpy arrays to get their element-wise product. 

<div class="alert alert-block alert-success"><b>Check your understanding: </b>

Consider the variable definitions for `a1` and `a2`. What does each print statment result in?

```
a1 = np.array([2, 1, 0])
a2 = np.array([1, 3, 5])

print(a1 * a2)
print(a1 + a2)
```

In [63]:
a1 = np.array([2, 1, 0])

In [64]:
a2 = np.array([1, 3, 5])

In [66]:
a1 * a2 

array([2, 3, 0])

In [67]:
a1 = list(a1)
a2 = list(a2)

In [69]:
a1 + a2 

[2, 1, 0, 1, 3, 5]

For the first line, the first element is `a1[0]*a2[0]`, the second element is `a1[1]*a2[1]`, and the third element is `a1[2]*a2[2]`.

For the second line, the first element is `a1[0]+a2[0]`, second is `a1[1]+a2[1]`, third is `a1[2]+a2[2]`

<div class="alert alert-block alert-success"><b>Check your understanding: </b>
    
What happens if `a1` and `a2` are lists? Consider each `print` statement separately.


The first print statement results in concatenation of the lists.

Second print statement results in a `TypeError`. This is because two lists cannot be multiplied. If you wanted to do element-wise multiplication, you would have to use `numpy` arrays (like in the previous exercise.)

## Logical comparisons

We can also do logical comparisons on whole arrays. For example, to find out if values in the array are greater than 0, we can write:

In [75]:
water_xyz

array([[ 0.     ,  0.     ,  0.11779],
       [ 0.     ,  0.75545, -0.47116],
       [ 0.     , -0.75545, -0.47116]])

In [71]:
print(water_xyz > 0)

[[False False  True]
 [False  True False]
 [False False False]]


This will print either `True` or `False` for each array element depending on whether the value of that element is greater than 10 or not.

To get every value in the array that is greater than 10, we can use this as a list of indices we want, or a *slice*.

In [76]:
water_xyz[water_xyz>0]

array([0.11779, 0.75545])

In [77]:
greater_than_0_values = water_xyz[water_xyz>0]
print(greater_than_0_values)

[0.11779 0.75545]


<div class="alert alert-block alert-success"><b>Check your understanding: </b>
    
- Create a 2D arrays of shape (3,3) with random numbers between -1 and 1. 
- Check whether each element in the array is larger or smaller than zero
    
**Hint 1:** you can use `np.random.uniform`, check its docstring!

**Hint 2:** you can first create the array with the correct number of elements, and then `reshape` it.

## Sorted arrays

You can sort array element with `np.sort`. Here we create 10 random numbers and sort them in ascending order:

In [ ]:
rand10 = np.random.rand(10)
rand10

In [ ]:
np.sort(rand10)

## Array Axes

<div class="alert alert-block alert-info">
    <b>Key point:</b> 
    
    
A `numpy` array can be thought of like a coordinates system. Axis 0 runs along the *ROWS*, while axis 1 runs along the *COLUMNS*.



<img src="https://i0.wp.com/andrewm4894.com/wp-content/uploads/2020/10/Annotation-2020-10-15-133235.jpg?w=486&ssl=1">

### Geometric center

Imagine we wanted to calculate the geometric center of our molecule. To do this, we would need to get the average x coordinate, the average y coordinate, and the average z coordinate.

We could calculate the mean of each column of an array using the `range` function and a `for` loop. This reminds  us of the `range` function and how `for` loops worked:

In [78]:
center = []

for dim in range(3):
    dim_mean = np.average(water_xyz[:, dim])
    center.append(dim_mean)

In [79]:
center

[0.0, 0.0, -0.27484333333333333]

In [81]:
np.average(water_xyz)

-0.09161444444444444

However, the `numpy.average` function will let us do that without a `for` loop.

In [82]:
np.average(water_xyz, axis= 0) # center of geometry

array([ 0.        ,  0.        , -0.27484333])

<div class="alert alert-block alert-success"><b> Check your understanding: </b>
    
    
Check out the [numpy documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.average.html) for the `average` function. Can you figure out what argument we might change to get the average of each column?

In [ ]:
np.average?

We will use the `axis` argument. If we do not specify `axis`, the mean of the entire array is computed. 

A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0, in our case ), and the second running horizontally across columns (axis 1).

For the `axis` argument, rows correspond to axis 1, and columns correspond to axis 0.

Now, the `average` function has returned a `numpy` array to us with the same number of elements as we have columns. The 0th element of the variable `column_averages` corresponds the mean of column index 0, the second number (index 1) corresponds to the mean of column index 1. 

<div class="alert alert-block alert-success"><b>Task 2.1: </b>
What does the following code do?

Assume we have imported `numpy` as `np`.

1. Write a short comment for each line.

2. Replace the variable `R` with your k-number.  (If your k-number doesn't work, try the closest even number)

3. Copy the resulting output from the print statement.
    
```
a = np.arange(1,R,2)
a_r = a.reshape(2, a.size//2)
a_mean = a_r.mean(axis=1)
print(a_mean)
``` 

### Center of mass

What if we wanted to calculate the center of mass of our water molecule? Let's first define the atom masses for our 3 atoms:

In [83]:
water_masses = [15.9994, 1.00784, 1.00784] 
#              oxygen, hydrogen, hydrogen

The `average` function has another optional argument that comes in handy: `weights`:

In [84]:
np.average?

Signature:
np.average(
    a,
    axis=None,
    weights=None,
    returned=False,
    *,
    keepdims=<no value>,
)
Docstring:
Compute the weighted average along the specified axis.

Parameters
----------
a : array_like
    Array containing data to be averaged. If `a` is not an array, a
    conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which to average `a`.  The default,
    axis=None, will average over all of the elements of the input array.
    If axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, averaging is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
weights : array_like, optional
    An array of weights associated with the values in `a`. Each value in
    `a` contributes to the average according to its associated weight.
    The weights array can either be 1-D (in which case its length must be
 

In [85]:
center_of_mass = np.average(water_xyz, # water coords
                 axis=0,               # specify axis = average x, y and z
                 weights=water_masses) # weighted average according to the atomic masses

In [86]:
center_of_mass

array([0.        , 0.        , 0.05189328])

## Calculating bonds with numpy 

Here is a function to calculate bond length that doesn't use `numpy` array features:

In [87]:
def calc_bond(rA, rB):
    """Calculate the distance between points A and B"""
    x_dist = (rA[0] - rB[0]) ** 2
    y_dist = (rA[1] - rB[1]) ** 2
    z_dist = (rA[2] - rB[2]) ** 2
    
    bond_length = np.sqrt(x_dist + y_dist + z_dist)
    
    return bond_length

In [88]:
atom_1 = np.array([ 0, 0.5, 0.4])           # atom 1 coords
atom_2 = np.array([ -0.4, 0.1, -0.2])       # atom 2 coords

In [91]:
v1 = (atom_1 - atom_2 )**2

In [94]:
np.sqrt(np.sum(v1))

0.8246211251235323

This function would work for both lists and `numpy` arrays, because it does not assume that `rA` and `rB` can do something like element-wise subtraction. 

### Built-in maths functions

Note we used the built-in function `np.sqrt`. There's a lot more maths functions where this came from. 
A few examples:

```
absx = np.abs(x)
x2 = np.power(x,2)
sqrtx = np.sqrt(x)
sinx = np.sin(x)
cosx = np.cos(x)
tanx = np.tan(x)
expx = np.exp(x)
lnx = np.log(x)
log10x = np.log10(x)
```

<div class="alert alert-block alert-success"><b>Check your understanding: </b>

Rewrite the `calc_bond` function to use the features of numpy arrays, like element-wise subtraction. 
    
```
    def calc_bond(rA, rB):
        """
        Calculate the distance between points A and B. 
        rA and rB must be numpy arrays."""
        #calculate bond length
        # ..
        return bond_length
```

Redefine your original distance function as `calc_bond_list`. Using both, we see that both functions give the same answer. 

In [ ]:
rA = oxygen_xyz
rB = water_xyz[:,1] # one hydrogen

In [ ]:
dist_vec = rA - rB

In [ ]:
bond_length = np.sqrt(np.sum(dist_vec**2)) # all array elements at once

In [ ]:
calc_bond(rA, rB) # O-H bond length

In [ ]:
calc_bond_list(rA, rB)

### Some more built-in functions 

Wait.. There's an even better version! 
You can use the `numpy` function `np.linalg.norm` which calculates the magnitude of a vector:

```
bond_length = np.linalg.norm(dist_vec)

```

<div class="alert alert-block alert-success"><b>Check your understanding: </b>

Rewrite the calc_bond function using `np.linalg.norm`.

## Calculating angles: bond angle of water

We can also calculate the angle between three atoms using the dot product. 

Going back to our water molecule coordinates, we will first define 2 vectors connecting our oxygen and hydrogen atoms, and then calculate the angle between them:


$$
\theta = arccos\left( \frac{\vec{OH_{1}} \cdot \vec{OH_{2}}} {|\vec{OH_{1}}||\vec{OH_{2}}|} \right)
$$

In [95]:
water_xyz

array([[ 0.     ,  0.     ,  0.11779],
       [ 0.     ,  0.75545, -0.47116],
       [ 0.     , -0.75545, -0.47116]])

Let's grab the atomic coordinates for oxygen and hydrogen atoms:

In [96]:
oxygen_xyz

array([0.     , 0.     , 0.11779])

In [97]:
hyd1_xyz, hyd2_xyz = water_xyz[1:,:]

In [98]:
hyd1_xyz 

array([ 0.     ,  0.75545, -0.47116])

In [99]:
hyd2_xyz

array([ 0.     , -0.75545, -0.47116])

Then calculate the `r_OH1` and `r_OH2` vectors:

In [100]:
r_OH1 = hyd1_xyz-oxygen_xyz
r_OH2 = hyd2_xyz-oxygen_xyz

We already know we can use `np.linalg.norm()` to calculate the norm of a vector.
`numpy` also has functions called `np.arccos()` and `np.dot()`.

In [101]:
dot = np.dot(r_OH1, r_OH2)                                    # dot product
norm = dot/ (np.linalg.norm(r_OH1) * np.linalg.norm(r_OH2))   # dividing by norm 
np.arccos(norm)                                               # arccos to get the angle  

1.817235608091645

<div class="alert alert-block alert-success"><b> Check your understanding: </b>
    
- In what units is the angle be returned by `np.arccos()`? Check the docstring.
- Using the `numpy` documentation online, Google or Stackoverflow, find out how to convert the angle in degrees. 

These are just a few of the calculations that can be done using numpy arrays. With numpy, you can easily calculate the geometrical properties of any molecule or object with Cartesian coordinates.


<div class="alert alert-block alert-success"><b> Task 2.2: </b>

Using the examples in this notebook, 

1. Write a function that takes as input the atomic coordinates of 3 atoms and calculates the corresponding angle between them. Include a docstring explaining the behaviour of the function.

2. Use it to calculate all 3 H-N-H angles (in degrees) for a molecule of ammonia - coordinates below:
```
ammonia_coord = np.array([[ -0.001 ,    -0.000 ,  -0.069],  # nitrogen 
                          [ -0.941 ,    0.001 ,   0.320],   # hydrogen 1
                          [  0.472 ,   -0.811 ,   0.322],   # hydrogen 2
                          [  0.468 ,    0.818 ,   0.321]])  # hydrogen 3
```

3. Print the average H-N-H  angle (in degrees). The result will be checked for consistency by the python interpreter on KEATS).
    
4. Add comments throughout your code to detail each step.

In [ ]:
def function(arg1, arg2):
    """ 
     this is a docstring. it explains function 
    """
    # function does things
    #more things
    return blah 


<div class="alert alert-block alert-info">
    <b>Key points:</b> 


`numpy` is a huge library: no matter what you need to do with an array, there's probably a built-in function for it. Google, Stack overflow and the `numpy` documentation can help you navigate the possibilities!


## Before the next Computational Lab: Plotting with Python

The notebook `CL2_NB3_plotting.ipynb` (in the CL2 folder) introduces some important python libraries used for plotting data: matplotlib and seaborn. We recommend you have a look at the notebook ahead of the next lab session to get familiarised with their style and syntax.

- Over the next few weeks, we will use matplotlib to plot data obtained throughout the computational labs, so you will get to see many examples! 

- Various assessed tasks from CL3-CL6 will require you to make and upload a plot to KEATS using python/matplotlib. 